# Be sure to update the environments in your "".vscode/setting.json"
#
#    "dev": {
#         "host": "https://blablabla.com",
#         "token": "yourToken"
#     },
#
# Tutorial:
# https://www.youtube.com/watch?v=RcxvrhQKv8I
#

#   %23 = '#'
@pairingSecret = 123456


### POST pairing request attempt
POST {{host}}/pairing/attempt
# POST https://l9gysa4p54.execute-api.eu-west-1.amazonaws.com/WootchDev/pair/attempt/
Authorization: {{token}}
content-type: application/json

{
    "secret": "{{pairingSecret}}",
}

### Get user
GET https://l9gysa4p54.execute-api.eu-west-1.amazonaws.com/WootchDev/user/
Authorization: {{token}}