# Be sure to update the environments in your "".vscode/setting.json"
#
#    "dev": {
#         "host": "https://blablabla.com",
#         "token": "yourToken"
#     },

# Do not put comma on the last item of a JSON object
# %23 = '#'

@pairingSecret = 9F9546

### POST pairing request attempt
POST {{host}}/pairing/attempt
Authorization: {{token}}
content-type: application/json

{
    "secret": "{{pairingSecret}}"
}

### Get user
GET {{host}}/user
Authorization: {{token}}